[versions]
spring-boot = "3.4.3"

[libraries]


[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot"}
spring-dependency-management = "io.spring.dependency-management:1.1.7"