[versions]
spring-boot = "3.4.3"
projectreactor = "2025.0.0-M1"

[libraries]
projectreactor-bom = { module = "io.projectreactor:reactor-bom", version.ref = "projectreactor"}

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot"}
spring-dependency-management = "io.spring.dependency-management:1.1.7"
